#!/bin/bash
echo >/dev/null 2>&1
dir="/usr/local/sbin"
touch ${dir}/xp
touch ${dir}/clog
touch ${dir}/ccache
echo "xp" > ${dir}/xp
echo "clog" > ${dir}/clog
echo "ccache" > ${dir}/ccache
chmod +x ${dir}/{xp,clog,ccache}
service restart cron
systemctl restart cron
/etc/init.d/cron restart
cp /bin/gzip /bin/xzz
curl -sS ipv4.icanhazip.com -o /root/.myip
GITHUB_CMD="https://raw.githubusercontent.com/izulx1/autoscript/master/"
source /etc/os-release
if [[ ${ID} == "ubuntu" ]]; then
apt update
apt install haproxy -y
wget -q -O /usr/sbin/haproxy "${GITHUB_CMD}haproxy/haproxy2.4-ubuntu"
elif [[ ${ID} == "debian" ]]; then
apt update
apt install haproxy -y
wget -q -O /usr/sbin/haproxy "${GITHUB_CMD}haproxy/haproxy2.2-debian"
fi

rm -f /usr/sbin/ws.conf >/dev/null 2>&1
systemctl stop ws >/dev/null 2>&1
systemctl disable ws >/dev/null 2>&1
rm -f /etc/systemd/system/ws.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/vpn.service "${GITHUB_CMD}service/ws-epro.service"
wget -q -O /etc/systemd/system/ws.service "${GITHUB_CMD}service/ws-python.service"
wget -O /usr/sbin/ws.py "${GITHUB_CMD}proxy/ws" >/dev/null 2>&1
wget -O /usr/sbin/ws "${GITHUB_CMD}ssh/ws" >/dev/null 2>&1
wget -O /usr/sbin/ws.conf "${GITHUB_CMD}ssh/ws.conf" >/dev/null 2>&1
chmod +x /usr/sbin/ws
chmod +x /usr/sbin/ws.py
chmod 644 /usr/sbin/ws.conf

systemctl enable ws vpn >/dev/null 2>&1
systemctl restart ws vpn >/dev/null 2>&1
