#!/bin/bash
repo="https://github.com/zhets/ScriptAutoInstall-xdxl/raw/main"
echo "Mendownload file yg di perlukan..."
sleep 2
wget -O /etc/systemd/system/ws-epro.service "${repo}/ws-epro.service"
wget -O /usr/bin/tun.conf "${repo}/tun.conf"
wget -O /usr/bin/ws-epro "${repo}/ws-epro"
chmod +x /usr/bin/ws-epro
chmod +x /usr/bin/tun.conf
echo "Done"
sleep 1

echo "Restarting Service Ws - ePRO"
sleep 2
systemctl enable ws-epro >/dev/null 2>&1
systemctl restart ws-epro
echo "Done"
sleep 1
menu
